version: '3'

services:
  db:
    container_name: db_library
    image: postgres:latest
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql_library_bin:/usr/lib/postgresql
      - postgresql_library_data:/var/lib/postgresql/data
      - ./library.sql:/docker-entrypoint-initdb.d/library.sql
    ports:
      - 55432:5432
    networks:
      - db

  pgadmin:
    container_name: pgadmin_library
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - postgresql_library_bin:/usr/lib/postgresql
      - pgadmin_root_prefs:/root/.pgadmin
      - pgadmin_working_dir:/var/lib/pgadmin
    ports:
      - 5050:5050
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  pgadmin_root_prefs:
    driver: local
  pgadmin_working_dir:
    driver: local
  postgresql_library_data:
    driver: local
  postgresql_library_bin:
    driver: local
